name = 'ragemp-mango-server'
host = '0.0.0.0'
port = 22005
players = 128
announce = false
gamemode = 'ragemp-mango'
website = 'https://github.com/ragemp-mango/ragemp-mango'
language = 'en'
description = 'A simple, lightweight, and powerful TypeScript framework for building RageMP servers.'
resources = ['core']
debug = true
